#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xEB6CCA1483FA74EC (infra-root@openstack.org)
#
Name     : python-ceilometerclient
Version  : 2.9.0
Release  : 35
URL      : http://tarballs.openstack.org/python-ceilometerclient/python-ceilometerclient-2.9.0.tar.gz
Source0  : http://tarballs.openstack.org/python-ceilometerclient/python-ceilometerclient-2.9.0.tar.gz
Source99 : http://tarballs.openstack.org/python-ceilometerclient/python-ceilometerclient-2.9.0.tar.gz.asc
Summary  : OpenStack Telemetry API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-ceilometerclient-bin
Requires: python-ceilometerclient-python3
Requires: python-ceilometerclient-license
Requires: python-ceilometerclient-python
Requires: iso8601
Requires: keystoneauth1
Requires: oslo.i18n
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
=====================================

%package bin
Summary: bin components for the python-ceilometerclient package.
Group: Binaries
Requires: python-ceilometerclient-license

%description bin
bin components for the python-ceilometerclient package.


%package license
Summary: license components for the python-ceilometerclient package.
Group: Default

%description license
license components for the python-ceilometerclient package.


%package python
Summary: python components for the python-ceilometerclient package.
Group: Default
Requires: python-ceilometerclient-python3

%description python
python components for the python-ceilometerclient package.


%package python3
Summary: python3 components for the python-ceilometerclient package.
Group: Default
Requires: python3-core

%description python3
python3 components for the python-ceilometerclient package.


%prep
%setup -q -n python-ceilometerclient-2.9.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532380954
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/python-ceilometerclient
cp LICENSE %{buildroot}/usr/share/doc/python-ceilometerclient/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ceilometer

%files license
%defattr(-,root,root,-)
/usr/share/doc/python-ceilometerclient/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
