#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-ceilometerclient
Version  : 2.4.0
Release  : 29
URL      : http://tarballs.openstack.org/python-ceilometerclient/python-ceilometerclient-2.4.0.tar
Source0  : http://tarballs.openstack.org/python-ceilometerclient/python-ceilometerclient-2.4.0.tar
Summary  : OpenStack Telemetry API Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-ceilometerclient-bin
Requires: python-ceilometerclient-python
Requires: iso8601
Requires: keystoneauth1
Requires: oslo.i18n
Requires: oslo.serialization
Requires: oslo.utils
Requires: pbr
Requires: python-keystoneclient
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Python bindings to the Ceilometer API
=====================================
This is a client library for Ceilometer built on the Ceilometer API. It
provides a Python API (the ``ceilometerclient`` module) and a command-line tool
(``ceilometer``).

%package bin
Summary: bin components for the python-ceilometerclient package.
Group: Binaries

%description bin
bin components for the python-ceilometerclient package.


%package python
Summary: python components for the python-ceilometerclient package.
Group: Default

%description python
python components for the python-ceilometerclient package.


%prep
%setup -q -n python-ceilometerclient-2.4.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489336085
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489336085
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ceilometer

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
